#!/bin/bash
tmp_branch=tmp_deploy
current_branch=$(git symbolic-ref --short -q HEAD)
git branch -D $tmp_branch
git checkout -b $tmp_branch
rm -rf package.json gulpfile.* bower.json app Gemfile Gemfile.lock Guardfile Rakefile config/ config.rb config.ru data/
cp -r build/* .
git add -A
git commit -m 'build'
git push -f origin $tmp_branch:gh-pages
echo return to branch $current_branch
git checkout $current_branch
npm install
bower install

